### ISSUE TITLE
HSIC option in README

### ISSUE THREAD

**Issue by guzy0324** [yifanzhang-pro/Matrix-SSL#6]
Thanks for your great work!
I notice an HSIC option in the README, which was removed from your codes in a previous commit.
I wonder if the HSIC is necessary to get the best checkpoint, and wonder whether `--mce_mu 1.0 --mce_lambd 1.0 --gamma 1.0` is the best hyperparameter setting.

**Comment by yifanzhang-pro** [comment]
we tried on it but didn't get benefit from it.

**Comment by guzy0324** [comment]
Another question is that I can't find the implementation of the first term in Eq. 13 of the [paper](https://arxiv.org/pdf/2305.17326).

**Comment by yifanzhang-pro** [comment]
The first term of Eq. 13 is canceled out with the Eq. 12.

We have fixed the README for removing the HSIC term, the HSIC term is not introduced in our method's default implementation.
